In [24]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [25]:
path = "c://ml_dataset/Churn_Modelling.csv"

In [26]:
data = pd.read_csv(path)

In [27]:
data.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [28]:
len(data.columns)

14

In [29]:
X = data.iloc[:,3:-1].values
y = data.iloc[:,-1].values

In [30]:
X[:10],y[:10]

(array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
        [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
        [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
        [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
        [850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1],
        [645, 'Spain', 'Male', 44, 8, 113755.78, 2, 1, 0, 149756.71],
        [822, 'France', 'Male', 50, 7, 0.0, 2, 1, 1, 10062.8],
        [376, 'Germany', 'Female', 29, 4, 115046.74, 4, 1, 0, 119346.88],
        [501, 'France', 'Male', 44, 4, 142051.07, 2, 0, 1, 74940.5],
        [684, 'France', 'Male', 27, 2, 134603.88, 1, 1, 1, 71725.73]],
       dtype=object),
 array([1, 0, 1, 0, 0, 1, 0, 1, 0, 0], dtype=int64))

In [31]:
#encoding the gender column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [32]:
X[:10]

array([[619, 'France', 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 0, 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [645, 'Spain', 1, 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [822, 'France', 1, 50, 7, 0.0, 2, 1, 1, 10062.8],
       [376, 'Germany', 0, 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [501, 'France', 1, 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [684, 'France', 1, 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

In [33]:
#OneHOtEncoding the country column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoders', OneHotEncoder(), [1])], remainder = "passthrough")
X = ct.fit_transform(X)

In [34]:
X[:10]

array([[1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [0.0, 0.0, 1.0, 608, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [1.0, 0.0, 0.0, 502, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [1.0, 0.0, 0.0, 699, 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [0.0, 0.0, 1.0, 850, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [0.0, 0.0, 1.0, 645, 1, 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [1.0, 0.0, 0.0, 822, 1, 50, 7, 0.0, 2, 1, 1, 10062.8],
       [0.0, 1.0, 0.0, 376, 0, 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [1.0, 0.0, 0.0, 501, 1, 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [1.0, 0.0, 0.0, 684, 1, 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

In [35]:
#Spliting data into training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [36]:
X_train[:10],X_test[:10]

(array([[0.0, 0.0, 1.0, 667, 0, 34, 5, 0.0, 2, 1, 0, 163830.64],
        [0.0, 1.0, 0.0, 427, 1, 42, 1, 75681.52, 1, 1, 1, 57098.0],
        [1.0, 0.0, 0.0, 535, 0, 29, 2, 112367.34, 1, 1, 0, 185630.76],
        [0.0, 0.0, 1.0, 654, 1, 40, 5, 105683.63, 1, 1, 0, 173617.09],
        [0.0, 0.0, 1.0, 850, 0, 57, 8, 126776.3, 2, 1, 1, 132298.49],
        [0.0, 1.0, 0.0, 776, 0, 37, 2, 103769.22, 2, 1, 0, 194099.12],
        [1.0, 0.0, 0.0, 807, 1, 47, 1, 95120.59, 1, 0, 0, 127875.1],
        [0.0, 0.0, 1.0, 598, 1, 41, 8, 0.0, 2, 1, 1, 161954.43],
        [0.0, 0.0, 1.0, 636, 1, 76, 9, 126534.6, 1, 1, 1, 39789.62],
        [1.0, 0.0, 0.0, 622, 0, 32, 6, 169089.38, 2, 1, 0, 101057.95]],
       dtype=object),
 array([[0.0, 1.0, 0.0, 597, 0, 35, 8, 131101.04, 1, 1, 1, 192852.67],
        [1.0, 0.0, 0.0, 523, 0, 40, 2, 102967.41, 1, 1, 0, 128702.1],
        [0.0, 0.0, 1.0, 706, 0, 42, 8, 95386.82, 1, 1, 1, 75732.25],
        [1.0, 0.0, 0.0, 788, 1, 32, 4, 112079.58, 1, 0, 0, 89368.59],
       

In [37]:
print(np.concatenate((y_train[:10].reshape(len(y_train[:10]),1),y_test[:10].reshape(len(y_test[:10]),1)),1))

[[0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]]


In [38]:
#feature scaling the independent variable
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [39]:
X_train[:5],X_test[:5]

(array([[-1.01460667, -0.5698444 ,  1.74309049,  0.16958176, -1.09168714,
         -0.46460796,  0.00666099, -1.21571749,  0.8095029 ,  0.64259497,
         -1.03227043,  1.10643166],
        [-1.01460667,  1.75486502, -0.57369368, -2.30455945,  0.91601335,
          0.30102557, -1.37744033, -0.00631193, -0.92159124,  0.64259497,
          0.9687384 , -0.74866447],
        [ 0.98560362, -0.5698444 , -0.57369368, -1.19119591, -1.09168714,
         -0.94312892, -1.031415  ,  0.57993469, -0.92159124,  0.64259497,
         -1.03227043,  1.48533467],
        [-1.01460667, -0.5698444 ,  1.74309049,  0.03556578,  0.91601335,
          0.10961719,  0.00666099,  0.47312769, -0.92159124,  0.64259497,
         -1.03227043,  1.27652776],
        [-1.01460667, -0.5698444 ,  1.74309049,  2.05611444, -1.09168714,
          1.73658844,  1.04473698,  0.8101927 ,  0.8095029 ,  0.64259497,
          0.9687384 ,  0.55837842]]),
 array([[-1.01460667,  1.75486502, -0.57369368, -0.55204276, -1.09168714,
    

In [40]:
X[:10]

array([[1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [0.0, 0.0, 1.0, 608, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [1.0, 0.0, 0.0, 502, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [1.0, 0.0, 0.0, 699, 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [0.0, 0.0, 1.0, 850, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [0.0, 0.0, 1.0, 645, 1, 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [1.0, 0.0, 0.0, 822, 1, 50, 7, 0.0, 2, 1, 1, 10062.8],
       [0.0, 1.0, 0.0, 376, 0, 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [1.0, 0.0, 0.0, 501, 1, 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [1.0, 0.0, 0.0, 684, 1, 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

In [41]:
#Building the ANN
#Making predictions on the test set
#Evaluating the ANN performance on the test set
class ChurnModelling:
    
    def __init__(self):
        
        self._X_train = X_train
        self._X_test = X_test
        self._y_train = y_train
        self._y_test = y_test
    

    def artificial_nn(self,bs,epochs):
        
        self._batch_size = bs
        self._epochs = epochs

        #initializing the ann
        self._ann = tf.keras.models.Sequential()
        #adding the first hidden layer
        self._ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))
        #adding the second hidden layer
        self._ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))
        #creating the output layer
        self._ann.add(tf.keras.layers.Dense(units = 1, activation = "sigmoid"))

        #compiling the ann
        self._ann.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])
        #training the ann
        self._ann.fit(self._X_train, self._y_train, batch_size = self._batch_size, epochs = self._epochs)
        
        
    def single_prediction(self):
        
        return self._ann.predict(sc.transform([[1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88]]))
    
    def test_set_prediction(self):
        
        self._y_pred = self._ann.predict(self._X_test)
        self._y_pred = (self._y_pred > 0.5)
        return np.concatenate((self._y_pred.reshape(len(self._y_pred),1), self._y_test.reshape(len(self._y_test),1)),1)
    
    def evaluation(self):
        
        from sklearn.metrics import confusion_matrix, accuracy_score
        cm = confusion_matrix(self._y_test,self._y_pred)
        accuracy = accuracy_score(self._y_test,self._y_pred)
        return f"Confusion Matrix : {cm} |  Accuracy : {accuracy}"

In [42]:
model = ChurnModelling()
model.artificial_nn(32,100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.6043 - accuracy: 0.6786
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4678 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4453 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4345 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4287 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4245 - accuracy: 0.7975
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4196 - accuracy: 0.8015
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4141 - accuracy: 0.8055
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4080 - accuracy: 0.8124
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3993 - accura

In [43]:
model._ann.predict(X_test)

63/63 [==============================] - 1s 2ms/step


array([[0.2963199 ],
       [0.39843723],
       [0.17660736],
       ...,
       [0.20002042],
       [0.16637555],
       [0.1482887 ]], dtype=float32)

In [44]:
print(model.single_prediction())

1/1 [==============================] - 0s 53ms/step
[[0.4411098]]


In [45]:
print(model.test_set_prediction())

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [46]:
print(model.evaluation())

Confusion Matrix : [[1493  102]
 [ 185  220]] |  Accuracy : 0.8565
